name: AbyssalChronicle
main: com.aaaaahhhhhhh.bananapuncher714.abyssalchronicle.AbyssalChronicle
version: 0.0.1
description: Bondrewd's Books
author: BananaPuncher714
api-version: 1.13
softdepend:
- "PlaceholderAPI"
- "BondrewdLikesHisEmotes"

commands:
  book:
    description: Read some books

permissions:
  abyssalchronicle.admin:
    description: "Admin permission"
    default: op
    children:
    - abyssalchronicle.book.command.update
    - abyssalchronicle.book.command.updateassets
    - abyssalchronicle.book.command.update.list.other
    - abyssalchronicle.book.command.openfor.other
    - abyssalchronicle.book.command.giveother.other
    - abyssalchronicle.book.command.setother
  abyssalchronicle.book.command:
    description: "Basic command permission"
    default: op
  abyssalchronicle.book.command.update:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command
  abyssalchronicle.book.command.updateassets:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command
  abyssalchronicle.book.command.list:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command
  abyssalchronicle.book.command.list.other:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.list
  abyssalchronicle.book.command.read:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command
  abyssalchronicle.book.command.read.other:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.read
  abyssalchronicle.book.command.readother:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.read.other
  abyssalchronicle.book.command.readother.other:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.readother
  abyssalchronicle.book.command.openfor:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.readother.other
  abyssalchronicle.book.command.openfor.other:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.openfor
  abyssalchronicle.book.command.give:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command
  abyssalchronicle.book.command.give.other:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.give
  abyssalchronicle.book.command.giveother:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.give.other
  abyssalchronicle.book.command.giveother.other:
    description: "Update the cache and resource pack"
    default: op
    children:
    - abyssalchronicle.book.command.giveother
  abyssalchronicle.book.command.set:
    description: "Set the current item to a book"
    default: op
    children:
    - abyssalchronicle.book.command.unset
  abyssalchronicle.book.command.setother:
    description: "Set the current item to a book"
    default: op
    children:
    - abyssalchronicle.book.command.set
  abyssalchronicle.book.command.unset:
    description: "Unset the current item"
    default: op
    children:
    - abyssalchronicle.book.command